- name: stop everything
  command: bash -lc "monit stop all"

- name: Reset DB
  command: chdir={{ be_app_path }}
           bash -lc "bundle exec rake db:drop db:create RAILS_ENV={{be_app_env}}"
  register: db_reset

- name: DB Reset Failed
  fail: msg="{{db_reset.stderr}}"
  when: db_reset.stderr

- name: start unicorns
  command: bash -lc "monit start all"
