---
- name: Import the yarn GPG key into apt
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn package deb repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install yarn
  apt:
    pkg: yarn
    state: installed
    update_cache: yes
