- name: Get PPA for latest Redis
  apt_repository:
    repo: ppa:chris-lea/redis-server
    update_cache: true


- name: Install Redis
  apt:
    name: redis-server
    state: latest

- name: kernel | set system overcommit policy
  sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: true
    state: present

- name: Register with monit
  template: src=redis.j2
            dest=/etc/monit/conf.d/redis
            mode=u=rw,g=r,o=r
  register: redis_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: redis_monit_config.changed
