- name: clone the app
  when: docker_app_repo is defined
  remote_user: "{{ deployer_user.name }}"
  git: dest={{ docker_app_path }}
       repo={{ docker_app_repo }}
       version={{ docker_app_branch }}
       accept_hostkey=true
       force=yes

- command: chdir={{ docker_app_path }}
           git ls-files Dockerfile
  register: docker_file

- command: chdir={{ docker_app_path }}
           git ls-files docker-compose.production.yml
  register: production_compose_file

- name: copy Dockerfile
  command: chdir={{ docker_app_path }}
           cp {{tapefiles_dir}}/Dockerfile {{docker_app_path}}
  when: docker_file.stdout.find('Dockerfile') == -1

- name: copy docker-compose file
  command: chdir={{ docker_app_path }}
           cp {{tapefiles_dir}}/docker-compose.production.yml {{docker_app_path}}
  when: docker_file.stdout.find('docker-compose.production.yml') == -1
