- name: Ensure puma owns it tmp dir
  file:
    path: "{{be_app_path}}/tmp"
    state: directory
    owner: deployer

- name: Ensure puma owns it pids dir
  file:
    path: "{{be_app_path}}/pids"
    state: directory
    owner: deployer

- name: Check if puma running
  shell: ps -ef | grep puma | grep -v grep
  register: puma_running
  changed_when: false
  ignore_errors: true

- name: Start Puma
  remote_user: "{{ deployer_user.name }}"
  command: bash -lc "sudo monit start puma"
  when: puma_running | failed

- name: Restart Puma
  remote_user: "{{ deployer_user.name }}"
  command: bash -lc "sudo monit restart puma"
  when: puma_running | success
