- name: Set up db config
  template: src=database.yml.j2 dest={{be_app_path}}/config/database.yml

# zzet.rbenv puts all the rbenv stuff in profile for some reason
# so we gotta use login shells to do this stuff
- name: Install bundle gems
  become_user: "{{ deployer_user.name }}"
  command: chdir={{ be_app_path }}
           bash -lc "RAILS_ENV={{be_app_env}} bundle install
           --without test development --no-binstubs --deployment"
  tags: [be_deploy, bundle]

- name: Ensure secrets.yml file present
  stat: path={{ be_app_path }}/config/secrets.yml
  register: secrets_file
  tags: [be_deploy]

- name: Ask for secrets.yml
  debug: msg="You've got to upload secrets.yml to {{be_app_path}}/config to continue"
  when: secrets_file.stat.exists != true
  tags: [be_deploy]

- name: Wait one day for secrets.yml to get put on the server
  wait_for: path={{be_app_path}}/config/secrets.yml state=present timeout=86400
  when: secrets_file.stat.exists != true

- name: Precompile Assets
  become_user: "{{ deployer_user.name }}"
  command: chdir={{ be_app_path }}
           bash -lc "bundle exec rake assets:precompile RAILS_ENV={{be_app_env}}"
  tags: [precompile_assets,be_deploy]
  when: precompile_assets
