---
- src: jnv.unattended-upgrades
  version: v1.0.1

- src: zzet.rbenv
  version: 2.1.3

- src: lxhunter.apt

- src: https://github.com/ANXS/postgresql
  name: ANXS.postgresql

- src: williamyeh.nodejs

- src: bennojoy.memcached

- src: jnv.mosh
