---
- src: jnv.unattended-upgrades
  version: v1.1.1

- src: Stouts.backup

- src: lxhunter.apt

- src: ANXS.postgresql
  name: ANXS.postgresql
  version: v1.8.0

- src: tersmitten.htop

- src: https://github.com/Oefenweb/ansible-sysfs
  name: ansible-sysfs
  version: v1.0.2
