---
- src: jnv.unattended-upgrades
  version: v1.1.1

- src: Stouts.backup

- src: lxhunter.apt

- src: https://github.com/ANXS/postgresql
  name: ANXS.postgresql
  version: v1.6.2

- src: geerlingguy.memcached
  version: 1.0.4

- src: tersmitten.htop
