---
- src: jnv.unattended-upgrades
  version: v1.1.1

- src: zzet.rbenv
  version: 2.1.7

- src: lxhunter.apt

- src: https://github.com/ANXS/postgresql
  name: ANXS.postgresql
  version: v1.3.0

- src: geerlingguy.memcached
  version: 1.0.4

- src: jnv.mosh

- src: tersmitten.htop

- src: nodesource.node
