---
- hosts: omnibox

  vars_files:
    - "{{tape_dir}}/vars/defaults.yml"
    - tape_vars.yml

  user: "{{ deployer_user.name }}"

  roles:
    - backend_checkout
    - backend_config
    - database_load
    - puma_activate
    - frontend_deploy
    # - delayed_job
