- name: Ensure developer keys are present in deployer's ssh keys
  authorized_key: key="{{ lookup('file', item) }}"
    user={{ deployer_user.name }}
    state=present
  with_fileglob:
    - "{{ playbook_dir }}/dev_keys/*"
