- name: Install upstart job
  template: src=dj_runner_upstart.j2
            dest=/etc/init/dj_runner_{{app_name}}.conf
  tags: [configure_dj_runner]
  register: dj_runner_installation

- name: register unicorn upstart script
  command: initctl reload-configuration
  when: dj_runner_installation.changed
  tags: [configure_dj_runner]

- include: monit_dj_install.yml
  when: use_monit

- name: Give deployer user access to DJ upstart jobs
  lineinfile: 'dest=/etc/sudoers
               state=present
               line="{{deployer_user}} ALL = (root) NOPASSWD: /sbin/{{item}} dj_runner_{{app_name}}"'
  with_items:
    - start
    - stop
    - restart
    - status
    - reload
  tags: [configure_dj_runner]

- include: upstart_delayed_job.yml
  when: not use_monit

- include: monit_delayed_job.yml
  when: use_monit
