- name: Enable nginx PPA
  apt_repository: repo=ppa:nginx/stable
  tags: [nginx]

- name: Install nginx
  apt: name=nginx state=present
  tags: [nginx]

- name: Configure nginx
  template: src=nginx_unicorn.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}
  notify: restart nginx
  tags: [nginx]

- include: monit.yml
  when: use_monit

- name: Ditch default nginx site enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: [nginx]

- name: Check out FE application
  remote_user: deployer
  git: dest={{ fe_app_path }}
       repo={{ fe_app_repo }}
       version={{ fe_app_branch }}
       accept_hostkey=true
  when: fe_app
  tags: [deploy, fe]
  register: fe_app_checkout
  
- name: Install node packages for web FE
  remote_user: deployer
  command: chdir={{fe_app_path}}
           bash -lc "npm install"
  tags: [deploy, fe]
  when: (fe_app_checkout is defined and fe_app_checkout.changed) or
        force_fe_build|default(false)

- name: Install grunt
  remote_user: deployer
  command: bash -lc "npm install grunt-cli -g"
  tags: [fe, grunt]
  when: (fe_app_checkout is defined and fe_app_checkout.changed) or
        force_fe_build|default(false)

- name: Build FE app
  remote_user: deployer
  command: chdir={{fe_app_path}}
           bash -lc "grunt build"
  tags: [deploy, fe]
  when: (fe_app_checkout is defined and fe_app_checkout.changed) or
        force_fe_build|default(false)

- name: Ensure nginx running
  remote_user: deployer
  service: name=nginx state=running
  tags: [deploy, fe]

- name: Ensure nginx is monitored
  monit: name=nginx state=monitored
  when: use_monit
