- name: build new container
  command: chdir={{ docker_app_path }}
    docker-compose build web --no-cache

- name: start new container
  command: chdir={{ docker_app_path }}
    docker-compose up --no-deps -d web
