- name: Install unicorn init.d script
  template: src=unicorn_init.j2
            dest=/etc/init.d/unicorn_{{app_name}}
            mode=u=rw,g=rx,o=rx

- name: Set up unicorn log dir
  file: path={{be_app_path}}/log state=directory owner=deployer

- name: Install unicorn config
  template: src=unicorn.rb.j2
            dest={{be_app_path}}/config/unicorn.rb

- name: Register monit config files
  template: src=unicorn_monit.j2
            dest=/etc/monit/conf.d/unicorn
            mode=u=rw,g=r,o=r
  register: unicorn_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: unicorn_monit_config.changed
