- name: Set up Puma log dir
  file: path={{be_app_path}}/log state=directory owner=deployer

- name: Install Puma config
  template: src=puma.production.rb.j2
            dest={{be_app_path}}/config/puma.production.rb

- name: Set up Puma pids dir
  file:
    path: "{{be_app_path}}/pids"
    state: directory
    owner: deployer

- name: Register Puma init script
  template:
    src: puma_init.j2
    dest: /etc/init.d/puma
    mode: u=rwx,g=r,o=r

- name: Register Puma monit config files
  template:
    src: puma_monit.j2
    dest: /etc/monit/conf.d/puma
    mode: u=rw,g=r,o=r
  register: puma_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: puma_monit_config.changed
